### ISSUE TITLE
Actividad 9 Diagrama de componentes

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-9-practica-de-arquitectura-dinamita#1]
Equipo Dinamita:
Diego Cruz Cruz 
Irvin Jiménez Sánchez 
Marco Uriel Rosas Garcia

[Diagrama de componentes_Equipo dinamita.pdf](https://github.com/user-attachments/files/18031391/Diagrama.de.componentes_Equipo.dinamita.pdf)

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica contiende todo calificacion 30%

**Comment by josealfredo79** [comment]
Sugerencia: Las actividades no pueden ser componentes, las actividades se implementan dentro de un metodo o funcion...
